### PR TITLE
Feature/refactoring

### PR DESCRIPTION
**Pull request by BohdanNikoletti**
1) Improved .gitignore
2) added analysis_options.yaml for lint
3) This pull request it preparation to new feature/shimmer_presentation_state that will be introduced in new commit

### CODE REVIEW

**Comment by hnvn** [comment]
Cool, thanks for your contribution

**Comment by hnvn** [comment]
I don't have experiences with analysis tools. Pardon my ignorance, could you explain the purpose of `analysis_options.yaml` you add?

**Comment by BohdanNikoletti** [comment]
> I don't have experiences with analysis tools. Pardon my ignorance, could you explain the purpose of `analysis_options.yaml` you add?

Thx for your response). I'll trie to explain usage of `analysis_options.yaml `. From the box Dart/Flutter project has some basic linter. That make hints about ` empty else code block or when you call a method without a required parameter`. 
And this is not enough. Cause with dart we can write `bad` code easily) Especially in open source projects. Thats why I decided to add linting tools. `analysis_options.yaml` - is a configuration file with default rules that linter can parse. This file is from official [flutter  repo](https://github.com/flutter/flutter/blob/master/analysis_options.yaml)
Some resources that should make it more clear:
1) [medium post]( https://medium.com/flutter-community/watch-your-code-dart-flutter-lint-55a697d01c8d)
2) [official dart doc](https://dart.dev/guides/language/analysis-options)
Hope I've provided enough information)

**Comment by hnvn** [comment]
Cool

**Pull request merged**
